language: python

sudo: false

os:
    - linux

python:
  - "3.6"

install:
    - pip install .[test]

script:
    - python setup.py check --restructuredtext
    - pytest -rx --flake8 --cov astropy_changelog astropy_changelog

after_success:
    - codecov
