language: python

sudo: false

os:
    - linux

python:
  - "3.6"

install:
    - pip install .

script:
    - pytest -rx --flake8 --cov astropy_changelog astropy_changelog

after_success:
    - codecov

